Fix panic caused by custom zls.json path
zigtools/zls pull request #1177
Opened 2023-05-08 16:03 UTC by Hanaasagi

2023-05-09 22:37 UTC, SuperAuguste requested changes

2023-05-09 22:37 UTC, SuperAuguste commented on src/configuration.zig
> +        var d = if (std.fs.path.isAbsolute(builtin_creation_dir.?))
I don't believe that this needs to be changed as openDir from cwd should handle absolute paths properly without this check :)

2023-05-11 19:39 UTC, leecannon approved these changes

2023-05-11 19:39 UTC, leecannon approved these changes

2023-05-13 05:53 UTC, SuperAuguste approved these changes
Sorry for the slow review, this looks great now, thanks! :))

2023-05-13 05:53 UTC, SuperAuguste approved these changes
Sorry for the slow review, this looks great now, thanks! :))

2023-05-13 05:53 UTC, merged