Restrict Maximum Whitespace in Inlay Hints
zigtools/zls pull request #1471
Opened 2023-09-26 02:01 UTC by Koranir

## Before:
![image](https://github.com/zigtools/zls/assets/101683475/9a07c7f7-c823-435d-b8c2-bb87ac6f4b0a)
## After:
![image](https://github.com/zigtools/zls/assets/101683475/48e98412-62ee-491d-bdaa-12e16202d782)

2023-09-26 02:10 UTC, xdBronch commented
imo the total number of characters should be restricted in cases like this, 68 characters dedicated to the type is quite a lot. maybe something like `const thing2: struct {...} = thing();` above a certain threshold? this is definitely an improvement though :+1:

2023-09-26 16:49 UTC, Techatrix requested changes
I would suggest to refactor this into a separate function.

Detecting long type hints and then reducing them to something like `struct { ... }` can be made as a separate contribution because this change is still better than status quo.

2023-09-26 16:49 UTC, Techatrix commented on src/features/inlay_hints.zig
> +    try reduced_type_str.ensureTotalCapacity(type_str.len);
this can be combined into a call to `std.ArrayListUnmanaged(u8).initCapacity(builder.arena, type_str.len)`

2023-09-26 16:49 UTC, Techatrix commented on src/features/inlay_hints.zig
> +                try reduced_type_str.append(' ');
this should call `appendAssumeCapacity`, same goes for the call a few lines below.

2023-09-27 19:28 UTC, Techatrix approved these changes

2023-09-27 21:46 UTC, nullptrdevs commented on src/features/inlay_hints.zig
> +    var reduced_type_str = try std.ArrayList(u8).initCapacity(arena, str.len);
```suggestion
    var reduced_type_str = try std.ArrayListUnmanaged(u8).initCapacity(arena, str.len);
```

2023-09-29 00:52 UTC, merged