Generate folding ranges for empty container types
zigtools/zls pull request #1474
Opened 2023-09-27 03:14 UTC by nullptrdevs

Resolves #1440

2023-09-27 19:27 UTC, Techatrix requested changes

2023-09-27 19:27 UTC, Techatrix commented on tests/lsp_features/folding_range.zig
> +        .{ .startLine = 0, .startCharacter = 16, .endLine = 1, .endCharacter = 0 },
the folding range should start after '{'
```suggestion
        .{ .startLine = 0, .startCharacter = 18, .endLine = 1, .endCharacter = 0 },
```

2023-10-01 06:08 UTC, SuperAuguste approved these changes
:)

2023-10-01 06:09 UTC, Techatrix approved these changes

2023-10-01 06:09 UTC, merged