Refactor enum_literal compls
zigtools/zls pull request #1493
Opened 2023-10-02 15:14 UTC by nullptrdevs

Not perfect, but functional .

2023-10-09 21:32 UTC, Techatrix requested changes
I did not perform any more checks on my suggestions than running tests so they may break something.
The only exception is the suggestion about the `@import` builtin resolution since the current testing infrastructure doesn't support multi file completion tests.

Could you also please remove your debugging related print statements including those that you have comment out.

2023-10-09 21:32 UTC, Techatrix commented on src/features/completions.zig
> +        }
```suggestion
        try node_type.getAllTypesWithHandlesArrayList(arena, types_with_handles);
```

2023-10-09 21:32 UTC, Techatrix commented on src/features/completions.zig
> +            }
```suggestion
            const node_type = try analyser.resolveTypeOfNode(.{ .node = type_expr_node, .handle = symbol_decl.handle }) orelse return;
            try node_type.getAllTypesWithHandlesArrayList(arena, types_with_handles);
```

2023-10-09 21:32 UTC, Techatrix commented on src/features/completions.zig
> +        .builtin_call_two => {
is this special case necessary? shouldn't the else case already handle this?

2023-10-09 21:32 UTC, Techatrix commented on src/features/completions.zig
> +        for (param_rcts) |prct| try types_with_handles.append(arena, prct);
```suggestion
        var fn_param_decl = Analyser.Declaration{ .param_payload = .{
            .func = type_expr_node,
            .param_index = @intCast(dot_context.fn_arg_index),
        } };
        const fn_param_decl_with_handle = Analyser.DeclWithHandle{ .decl = &fn_param_decl, .handle = symbol_decl.handle };
        const param_type = try fn_param_decl_with_handle.resolveType(analyser) orelse return;
        try types_with_handles.append(arena, param_type);
```

2023-10-09 21:32 UTC, Techatrix commented on src/features/completions.zig
> +            }
```suggestion
            try node_type.getAllTypesWithHandlesArrayList(arena, types_with_handles);
```

2023-10-09 21:32 UTC, Techatrix commented on src/features/completions.zig
> +    text_index: usize,
`source index` is the term used to refer to byte indices into document source code throughout the codebase.
```suggestion
    source_index: usize,
```

2023-10-09 21:32 UTC, Techatrix commented on src/features/completions.zig
> +            if (std.mem.eql(u8, container.handle.tree.tokenSlice(field.ast.main_token), alleged_field_name)) {
this can be `if (!std.mem.eql(...)) continue` to avoid extra indentation.

2023-10-10 00:53 UTC, nullptrdevs commented
Applied all of the above, multi file completions seem to work.

2023-10-10 03:42 UTC, Techatrix requested changes
second round of refactoring and simplification. tests still pass...

2023-10-10 03:42 UTC, Techatrix commented on src/features/completions.zig
> +        var node_type = try analyser.resolveTypeOfNode(.{ .node = decl_node, .handle = decl.handle }) orelse continue;
```suggestion
        var node_type = try decl.resolveType(analyser) orelse continue;
```

2023-10-10 03:42 UTC, Techatrix commented on src/features/completions.zig
> +        }
```suggestion
        const member_decl = try analyser.lookupSymbolContainer(.{ .node = node, .handle = container.handle }, alleged_field_name, .field) orelse continue;
        const member_type = try member_decl.resolveType(analyser) orelse continue;
        try types_with_handles.append(arena, member_type);
```

2023-10-10 03:42 UTC, Techatrix commented on src/features/completions.zig
> +    return;
```suggestion
```

2023-10-10 03:42 UTC, Techatrix commented on src/features/completions.zig
> +    }
```suggestion
    const type_expr = try symbol_decl.resolveType(analyser) orelse return;
    if (type_expr.isFunc()) {
        const fn_proto_node = type_expr.type.data.other;
        var buf: [1]Ast.Node.Index = undefined;
        const full_fn_proto = symbol_decl.handle.tree.fullFnProto(&buf, fn_proto_node) orelse return;
        if (dot_context.likely == .enum_literal) { // => we need f()'s return type
            if (full_fn_proto.ast.return_type == 0) return;
            const node_type = try analyser.resolveTypeOfNode(.{ .node = full_fn_proto.ast.return_type, .handle = symbol_decl.handle }) orelse return;
            try node_type.getAllTypesWithHandlesArrayList(arena, types_with_handles);
            return;
        }
        var fn_param_decl = Analyser.Declaration{ .param_payload = .{
            .func = fn_proto_node,
            .param_index = @intCast(dot_context.fn_arg_index),
        } };
        const fn_param_decl_with_handle = Analyser.DeclWithHandle{ .decl = &fn_param_decl, .handle = symbol_decl.handle };
        const param_type = try fn_param_decl_with_handle.resolveType(analyser) orelse return;
        try types_with_handles.append(arena, param_type);
        return;
    }
    try type_expr.getAllTypesWithHandlesArrayList(arena, types_with_handles);
```

2023-10-10 03:42 UTC, Techatrix commented on src/features/completions.zig
> +    if (try analyser.getFieldAccessType(handle, loc.end, &tokenizer)) |result| {
reduce indentation:
```suggestion
const result = try analyser.getFieldAccessType(handle, loc.end, &tokenizer) orelse return;
```

2023-10-10 04:28 UTC, nullptrdevs commented
Ditto

2023-10-10 04:33 UTC, Techatrix commented
LGTM, hopefully nothing has regressed through these changes.
I will run some fuzzing overnight so that we don't introduce any new crashes.

2023-10-11 01:39 UTC, Techatrix approved these changes
Fuzzing only reported a single crash which was unrelated to this PR. (InternPool related)

2023-10-11 03:03 UTC, merged