update to new module system
zigtools/zls pull request #1698
Opened 2024-01-03 04:28 UTC by xdBronch

breaking changes from https://github.com/ziglang/zig/pull/18160
made corresponding prs in [known-folders](https://github.com/ziglibs/known-folders/pull/43) and [diffz](https://github.com/ziglibs/diffz/pull/19), iiuc the hashes i used in the zon will still work once the prs are merged, github magic or whatever :p

2024-01-03 04:28 UTC, xdBronch commented
forgot to update the min zig version of course lol

2024-01-03 04:33 UTC, xdBronch commented
also there seems to be a regression relating to build runners being cached so zls cant really use its build runner correctly meaning module imports are broken

2024-01-03 11:35 UTC, Techatrix requested changes

2024-01-03 11:35 UTC, Techatrix commented on build.zig
> +pub fn build(b: *std.Build) !void {
The `*std.Build` expression is analyzed before the version check which means that  you will get a `container 'std' has no member called 'Build'` error when building with old zig versions like 0.9.0. The following changes will ensure that the version check is always analyzed first.

```suggestion
const Build = blk: {
    const current_zig = builtin.zig_version;
    const min_zig = std.SemanticVersion.parse(min_zig_string) catch unreachable;
    if (current_zig.order(min_zig) == .lt) {
        @compileError(std.fmt.comptimePrint("Your Zig version v{} does not meet the minimum build requirement of v{}", .{ current_zig, min_zig }));
    }
    break :blk std.Build;
};

pub fn build(b: *Build) !void {
```

2024-01-03 11:35 UTC, Techatrix commented on build.zig
> +        .target = target,
This breaks cross compilation because the `zls_gen` executable need to always target the host machine.
```suggestion
        .target = b.host,
```

2024-01-05 13:07 UTC, Techatrix requested changes

2024-01-05 13:07 UTC, Techatrix commented on src/build_runner/master.zig
> +    const host = try std.zig.system.resolveTargetQuery(.{});
This doesn't match what I have found in zig's [build_runner.zig](https://github.com/ziglang/zig/blob/04ac028a2cd20ea430dd6a05b956363ec182b6ff/lib/build_runner.zig#L49-L52). `query` appears to store the parameter that has been passed to `resolveTargetQuery`.
```suggestion
    const host: std.Build.ResolvedTarget = .{
        .query = .{},
        .result = try std.zig.system.resolveTargetQuery(.{}),
    };
```
The call to `std.Build.create` will also need to be adjusted.

2024-01-05 13:44 UTC, xdBronch commented
oh thats funny, the [changes](https://github.com/ziglang/zig/pull/17431) to the expectEqual function meant to make them better to work with are actually causing CI to fail

2024-01-05 15:29 UTC, nullptrdevs commented
Past experience tells me it might be a good idea to rename the current build runner and use it with zig versions < 2030, some/certain projects only update in large increments.

2024-01-05 15:39 UTC, Techatrix commented
> Past experience tells me it might be a good idea to rename the current build runner and use it with zig versions < 2030, some/certain projects only update in large increments.

Any projects that doesn't target the latest Zig shouldn't use the latest ZLS as well.
I would rather have the multi build runner system removed at some point instead of extending it with more versions.
Previous Discussion on this: https://github.com/zigtools/zls/issues/1020#issuecomment-1772738942

2024-01-05 15:41 UTC, nullptrdevs commented
> > Past experience tells me it might be a good idea to rename the current build runner and use it with zig versions < 2030, some/certain projects only update in large increments.
> 
> Any projects that doesn't target the latest Zig shouldn't use the latest ZLS as well. I would rather have the multi build runner system removed at some point instead of extending it with more versions. Previous Discussion on this: [#1020 (comment)](https://github.com/zigtools/zls/issues/1020#issuecomment-1772738942)

Yeah, well #1396

2024-01-05 16:09 UTC, xdBronch commented
realistically it doesnt matter since the 2 commits are like a day apart but updating the minimum version to the expectEqual change isnt required afaict. i tested earlier and the updated tests work with the new and old expectEqualDeep

2024-01-05 16:12 UTC, Techatrix commented
FYI, I have edited your PR and done the following:
- updated the minimum build version again
- squashed some of your commits
- updated `build.zig.zon` so that the commit hashes refer to the master/main branch
- updated everything nix related

2024-01-05 16:13 UTC, Techatrix commented
> realistically it doesnt matter since the 2 commits are like a day apart but updating the minimum version to the expectEqual change isnt required afaict. i tested earlier and the updated tests work with the new and old expectEqualDeep

The minimum build version had to be updated anyway because of [ziglang/#18438](https://github.com/ziglang/zig/issues/18438), so I did it just in case.

2024-01-05 16:17 UTC, xdBronch commented
ah i actually did something a little sneaky before :smile:
i made the minimum version refer to the commit that fixed that issue but the comment refer to the big module pr. in hindsight it probably didnt make much sense to do so but i was being overly pedantic, the comment above says `document the latest breaking change that caused a change to the string below:` but it was a bug fix not a breaking change :p 
either way it doesnt matter because now CI is failing because of yet another breaking change haha

2024-01-05 16:39 UTC, Techatrix approved these changes
Everything looks to be in order finally.
The only thing missing are the nix flakes which I will update in a follow up PR once https://github.com/mitchellh/zig-overlay has updated again.

2024-01-05 16:41 UTC, merged