Fix fallback logic in `analysis.getPositionContext`
zigtools/zls pull request #1754
Opened 2024-02-09 18:37 UTC by nullptrdevs

Most lines are indented, ie `line[0] == ' '`(a space).

Tokenizing `line` as the sole buffer returns location offsets relative/within to that line, but are expected to be indexes within `handle.tree.source` .

2024-02-09 19:28 UTC, Techatrix requested changes
This looks like something that could be covered by a test case in [position_context.zig](https://github.com/zigtools/zls/blob/master/tests/utility/position_context.zig).

2024-02-11 07:14 UTC, nullptrdevs commented
Having done this makes me realize having that logic is very dicey and
https://github.com/zigtools/zls/blob/05ae41e3f4af684628c97a921b85e07d921f38e2/src/features/completions.zig#L1338
should just use `tok_loc.end` or 
https://github.com/zigtools/zls/blob/05ae41e3f4af684628c97a921b85e07d921f38e2/src/features/completions.zig#L1197
look_ahead = true here (haven't tested for side effects).

2024-02-19 00:39 UTC, Techatrix approved these changes

2024-04-13 22:31 UTC, llogick commented
This is a low priority PR, the test changes are worth having, but in my opinion the fallback logic shouldn't exist (and obviously nothing depends on it currently).

2024-11-12 20:19 UTC, closed without merging