Struct init type hints
zigtools/zls pull request #1778
Opened 2024-02-17 21:43 UTC by nullptrdevs

Partial #1531

Techatrix you get to name the config option :)

2024-02-17 21:59 UTC, nullptrdevs commented on src/features/inlay_hints.zig
> +                const name_token = tree.firstToken(value_node) - 2; // get --------------^^^^
Note to self: Disable inlay hints before aligning comments ...

2024-02-18 02:43 UTC, Techatrix commented
> Techatrix you get to name the config option :)

Coming up with a name for a config options is definitely not my strong suit. (╥﹏╥)
I would suggest something like "inlay_hints_show_anonymous_literal_field_type" or "inlay_hints_show_anon_literal_field_type"?

2024-02-18 03:01 UTC, nullptrdevs commented
Are they anon literals though? + it works for regular `S{.name<T> = ..}` too

2024-02-18 03:42 UTC, Techatrix commented
> Are they anon literals though? + it works for regular `S{.name<T> = ..}` too

oh right, then "inlay_hints_show_struct_literal_field_type"?

2024-02-19 00:38 UTC, Techatrix requested changes

2024-02-19 00:38 UTC, Techatrix commented on src/features/inlay_hints.zig
> +            const struct_init = tree.fullStructInit(&buffer, node) orelse return;
```suggestion
            const struct_init = tree.fullStructInit(&buffer, node).?;
```

2024-02-19 00:38 UTC, Techatrix commented on src/features/inlay_hints.zig
> +                );
```suggestion
                const decl = (try builder.analyser.getSymbolEnumLiteral(builder.arena, builder.handle, name_loc.start, name)) orelse continue;
                const ty = try decl.resolveType(builder.analyser) orelse continue;
                const type_str: []const u8 = try std.fmt.allocPrint(builder.arena, "{}", .{ty.fmt(builder.analyser)});
                if (type_str.len == 0) continue;
                try appendTypeHintString(
                    builder,
                    name_token,
                    try reduceTypeWhitespace(type_str, builder.arena),
                );
```

2024-02-19 01:38 UTC, Techatrix approved these changes

2024-02-19 01:39 UTC, merged