Check the boolean `gop.found_existing` only once
zigtools/zls pull request #1856
Opened 2024-04-11 18:41 UTC by ThisAccountHasBeenSuspended

2024-04-11 18:52 UTC, nektro approved these changes

2024-04-12 18:03 UTC, Techatrix requested changes

2024-04-12 18:03 UTC, Techatrix commented on src/DocumentScope.zig
> -            // a token with a doc comment takes priority.
this comment should not be removed

2024-04-13 21:04 UTC, Techatrix approved these changes

2024-04-13 21:04 UTC, merged