perf: Improve local variable reference finding
zigtools/zls pull request #1917
Opened 2024-06-13 02:34 UTC by WillLillis

This PR improves the time to find references and rename local variables. As suggested by @Techatrix in the discord, for certain cases the search for references can be limited to the current document rather than the entire project. After some brief testing with function-local variables in the zls project I saw a typical 4,500ms to <10ms improvement with debug builds. Testing with some of the larger files in zig itself, I saw a typical 20,000ms to 2,500ms improvement. Greater improvements are seen when using a `ReleaseSafe` build. I can spend some time gathering more numbers if that would be helpful :)

2024-06-16 17:36 UTC, WillLillis commented
Took another pass over this and sped up private container-scoped decls as well. In my own testing this didn't break anything/ cause any refs to be missed, but would appreciate a second look-over.

2024-06-16 20:11 UTC, Techatrix requested changes
After taking a closer look at the references code, I realized that this extra logic should be moved [here](https://github.com/zigtools/zls/blob/b4f4d35354f39fd190b9ce681c75affafaa0a1ab/src/features/references.zig#L239) since its the only place where `workspace` is being used. This makes it clear that we only need to handle the case where the declaration is an `.ast_node`. Otherwise the logic looks fine.

---

The code looked a bit different from what I would have written so I left some suggestion on how to write it in a more "idiomatic" style. In the end, this is probably what I would have written:
```zig
const workspace = if (request == .highlight) false else blk: {
    const doc_scope = try handle.getDocumentScope();
    const scope_index = Analyser.innermostBlockScopeIndex(doc_scope, source_index).unwrap() orelse break :blk true;
    break :blk switch (doc_scope.getScopeTag(scope_index)) {
        .function, .block => false,
        .container, .container_usingnamespace => decl.isPublic(),
        .other => true,
    };
};
```
Hope that helps :shrug:

2024-06-16 21:17 UTC, WillLillis commented
> After taking a closer look at the references code, I realized that this extra logic should be moved [here](https://github.com/zigtools/zls/blob/b4f4d35354f39fd190b9ce681c75affafaa0a1ab/src/features/references.zig#L239) since its the only place where `workspace` is being used. This makes it clear that we only need to handle the case where the declaration is an `.ast_node`. Otherwise the logic looks fine.
> 
> The code looked a bit different from what I would have written so I left some suggestion on how to write it in a more "idiomatic" style. In the end, this is probably what I would have written:
> 
> ```zig
> const workspace = if (request == .highlight) false else blk: {
>     const doc_scope = try handle.getDocumentScope();
>     const scope_index = Analyser.innermostBlockScopeIndex(doc_scope, source_index).unwrap() orelse break :blk true;
>     break :blk switch (doc_scope.getScopeTag(scope_index)) {
>         .function, .block => false,
>         .container, .container_usingnamespace => decl.isPublic(),
>         .other => true,
>     };
> };
> ```
> 
> Hope that helps 🤷

That was really helpful, thank you! Getting this kind of feedback is always really appreciated so that so my cide can be cleaner moving forward :). I think I'll do another read through the language reference to brush up as well.

2024-06-16 21:40 UTC, Techatrix requested changes

2024-06-16 21:40 UTC, Techatrix commented on src/features/references.zig
> +            const source_index = offsets.positionToIndex(curr_handle.tree.source, request.position(), encoding);
The scope should be looked up where the declaration is located and not where the cursor is. The symbol/decl may be in a different file that where the request was initiated.
```suggestion
            const source_index = offsets.tokenToIndex(decl_handle.handle.tree, decl_handle.nameToken());
```

Here is an example that can cause a crash:
```zig
// A.zig
pub const Foo = struct {};
```
```zig
// B.zig
const A = @import("A.zig");
fn foo() void {
    _ = A.Foo;
    //     ^ find all references here
}
```

2024-06-18 15:26 UTC, Techatrix approved these changes

2024-06-18 15:26 UTC, merged