ability to highlight global var declarations
zigtools/zls pull request #655
Opened 2022-09-15 07:16 UTC by nullptrdevs

this probably looks rough but does highlight everything declared with "var" at the root level

Closes #540

2022-09-15 09:30 UTC, Techatrix requested changes
nice!
But you should also update the README.

2022-10-10 03:55 UTC, SuperAuguste commented
Could you please force push on this branch to remove all the extraneous commits?

2022-10-10 05:11 UTC, SuperAuguste commented
I think we can just squash and merge, no worries :)

2022-10-10 05:12 UTC, SuperAuguste approved these changes

2022-10-10 05:13 UTC, merged