Add target to Env struct
zigtools/zls pull request #656
Opened 2022-09-15 13:30 UTC by jcmoyer

Fixes an issue where zls couldn't parse the output from `zig env` causing it to repeatedly print

```
debug: (store ): Cannot resolve std library import, path is null.
```

and fail to autocomplete.

See: https://github.com/ziglang/zig/pull/11741

2022-09-15 20:58 UTC, SuperAuguste commented
Website CI is broken; I'll merge this when it's fixed :)

2022-09-17 19:29 UTC, leecannon requested changes
This will need to be `target: ?[]const u8 = null,` to work with older zig versions, including CI atm.

2022-09-17 20:38 UTC, nektro commented
set `ignore_unknown_fields = true` in our `std.json.ParseOptions` instead

2022-09-18 06:41 UTC, jcmoyer commented
I'm not sure which behavior is more preferrable (add `target` field or use `ignore_unknown_fields`). I only became aware of the `zig env` change explicitly because `ignore_unknown_fields` wasn't being used.

2022-09-18 18:03 UTC, leecannon approved these changes

2022-09-18 18:05 UTC, merged