Adds a 'format to camelCase' codeaction for function names
zigtools/zls pull request #679
Opened 2022-09-27 21:37 UTC by NuclearPhone

Does as the title says, this PR adds a code action that reformats non-camelCase function names to be camelCase.
 ___
![camelcase1](https://user-images.githubusercontent.com/19677138/192639733-f1d527a3-dce8-41a8-a7d5-d9a00008f90a.gif)
![camelcase2](https://user-images.githubusercontent.com/19677138/192639739-1838f358-dcd6-4059-9c4b-fc11056d0330.gif)

2022-09-28 00:46 UTC, Techatrix requested changes
Thanks for you PR! It's great to see more code actions getting integrated. There are "a few" issues though.
If you are interested you can also add code actions for `Type functions should be PascalCase` or `A ./ is not needed in imports`.

2022-09-28 00:46 UTC, Techatrix commented on src/code_actions.zig
> +        .kind = .QuickFix,
this should be keep at SourceFixAll

2022-09-28 00:46 UTC, Techatrix commented on src/code_actions.zig
> +        } else if (std.mem.startsWith(u8, msg, "Functions should")) {
i thinks its better if you check for the entire message `Functions should be camelCase`

2022-09-28 00:46 UTC, Techatrix commented on src/code_actions.zig
> +        .kind = .SourceFixAll,
I am unsure if this should be part of autofix (indicated by `SourceFixAll`). Can you set it to `QuickFix` while i think about it being included in autofix.

2022-09-28 00:46 UTC, Techatrix commented on src/code_actions.zig
> +        if (c == '_') num_separators += 1;
you can refactor this into `const num_separators = std.mem.count(u8, identifier, "_")`

2022-09-28 00:46 UTC, Techatrix commented on src/code_actions.zig
> +
You don't need this code because the identifier location is in `loc`.

2022-09-28 00:46 UTC, Techatrix commented on src/code_actions.zig
> +    }
this causes a index out of bound error when you have an identifier which ends with an underscore like
```zig
fn foo_bar_baz_() void {}
```

2022-09-28 01:11 UTC, NuclearPhone commented
Thanks for the feedback; I'll get to fixing my error-ridden code. In the future i'll pay more attention to proof-reading.

2022-09-29 03:54 UTC, Techatrix commented on src/code_actions.zig
> +        .kind = .QuickFix,
I think your latest commit touched the wrong place. 
Set this location https://github.com/NuclearPhone/zls/blob/39ea5869a377eeec71fe333f2ee264fac7cf2bbb/src/code_actions.zig#L85 to `.QuickFix`.
And set this location https://github.com/NuclearPhone/zls/blob/39ea5869a377eeec71fe333f2ee264fac7cf2bbb/src/code_actions.zig#L176 to `.SourceFixAll`.

2022-09-29 18:35 UTC, Techatrix approved these changes
nice

2022-09-30 04:05 UTC, merged