Allow tabs for the indentation added by code actions.
zigtools/zls pull request #684
Opened 2022-09-28 17:12 UTC by IntegratedQuantum

I just tested #673 in my codebase and the indentation was messed up:
Before:
```zig
								var index = getIndex(x, y, z);
								var otherIndex = getIndex(otherX, otherY, otherZ);
```
After:
```zig
								var index = getIndex(x, y, z);
        _ = index;
								var otherIndex = getIndex(otherX, otherY, otherZ);
```

The thing is: My codebase uses tabs (which is allowed as of stage2).

Normally I would have just made an issue about it, but since this is quite easy to fix, I thought I might just do it myself.

2022-09-28 22:18 UTC, nektro commented
if tabs are allowed by stage2 then its a bug, theyre supposed to be a hard error

2022-09-28 22:24 UTC, leecannon commented
https://github.com/ziglang/zig/wiki/FAQ#why-does-zig-force-me-to-use-spaces-instead-of-tabs

> Currently, the stage1 parser rejects tabs and the stage2 parser accepts them. What will make it into the final language specification? It isn't decided yet and it doesn't really matter. Just run zig fmt on save.

2022-09-28 22:28 UTC, nektro commented
https://github.com/ziglang/zig-spec/issues 38

2022-09-28 23:03 UTC, nektro commented
stage1 isnt a concern since stage2 is now the default compiler. tabs do not align to the spec or `zig fmt` so zls has no reason to support this.

2022-09-29 18:08 UTC, SuperAuguste commented
I'll weigh in here; I frankly could not care less about what indentation someone uses in Zig. If this improves user experience then I'm all good with it.

2022-09-29 18:15 UTC, SuperAuguste requested changes
I really dislike the approach taken here; wouldn't the line slice be guaranteed to simply be the tabs needed for indentation if your document's indentation is set to tabs removing the need for the `additional_indent` hack? From a cursory glance I *believe* a solution that like should be effective. :)

2022-09-29 18:58 UTC, IntegratedQuantum commented
Yeah I don't really like it either. But in this case I think it is needed:
```zig
    fn(unusedVar: xy) void {
        _ = unusedVar; // ← needs more indentation then the previous line.
```
I could put this inside a function that returns the full indentation, but that would require additional allocations.
So just using 2 separate strings seems like the best solution to me.

2022-09-30 09:01 UTC, IntegratedQuantum commented
> That does make sense.. what if the last param of createDiscardText be a bool, do_add_block_indent or block_indent_needed and have the logic for that there? (not allocations, the `var additional_indent = ..`

Yeah, I thought about that, but to figure out if tabs are used I need the entire file(The function in question might be in file scope, without indentation, so I cannot determine if tabs are used from just the indentation of the function declaration). So in that case I would need two new parameters instead of one.

But now that I think about it, I might just pass the builder in there instead of passing only the allocator.

​

I also noticed another issue, that I'll try to fix:
```
someOtherCode();var x: u8 = 0; // ← sadly this is allowed in zig.
                _ = x; // ← previous implementation (not that bad)
someOtherCode();_ = x; // ← my implementation (bad)
```
Even worse for `const z = struct{fn x(y: u8) void {}};`

2022-09-30 10:18 UTC, IntegratedQuantum commented
Done.
I also made it work with other indentations (some people prefer 2 spaces for indentation).

2022-10-01 00:15 UTC, SuperAuguste commented
Please resolve conflicts :)

2022-10-12 10:39 UTC, IntegratedQuantum commented
I fixed the merge conflicts like a week ago. I'm guessing you didn't get a notification for that?

2022-10-13 02:41 UTC, SuperAuguste commented
Sorry in the middle of midterms and work, LGTM.

2022-10-13 02:41 UTC, merged