Added textDocument/foldingRange
zigtools/zls pull request #718
Opened 2022-10-24 01:32 UTC by SasLuca

A simple initial implementation of `textDocument/foldingRange` that enables folding matching multi-line curly brace ranges.

2022-10-24 15:22 UTC, SuperAuguste requested changes

2022-10-24 17:49 UTC, SasLuca commented on src/Server.zig
> +        log.warn("Trying to get inlay hint of non existent document {s}", .{req.params.textDocument.uri});
Yeah, silly copy paste issue. Fixed it!

2022-10-24 18:22 UTC, leecannon commented
I actually get less folding regions with this PR than without it. I assume this is to do with having https://marketplace.visualstudio.com/items?itemName=tiehuis.zig as well as zls-vscode.

## Without
![old](https://user-images.githubusercontent.com/2286349/197597775-ec675f4f-5633-4afe-a34e-7661edc14054.png)

## With
![new](https://user-images.githubusercontent.com/2286349/197597800-2bab458a-8911-45a0-99c1-8ba80431107a.png)

2022-10-24 18:35 UTC, SasLuca commented
I get no folding regions at all without this change. I use both the zig and zls-vscode plugins. Do you use just one?

Seems like the difference between the 2 images is that multiline parens pairs are also given a fold option in the first one, I could add this easily.

2022-10-24 18:43 UTC, leecannon commented
I use both the zig and zls extensions, as far as I can remember i've always had folding regions no idea why.

2022-10-25 10:03 UTC, InKryption commented
@leecannon Probably the current indentation you're seeing is because you have `"editor.foldingStrategy": "indentation"`, whereas @SasLuca probably has `"editor.foldingStrategy": "auto"`. Overall I think this is going to be better, because this can avoid providing folding regions that don't make sense.

2022-10-25 10:30 UTC, SasLuca commented
Yeah, I think the main issue is just what regions we want to provide folding for. Right now I do it for scopes and for comments like `//#region`. Will probably add support for multi-line comments and maybe for paren pairs that span multiple lines.

2022-10-25 14:35 UTC, SuperAuguste approved these changes
LGTM! :)

2022-10-25 14:35 UTC, merged